name: CI/CD Pipeline for .NET API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build FlyPack.Presentation/FlyPack.Presentation.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test --configuration Release

    - name: Publish the API
      run: dotnet publish FlyPack.Presentation/FlyPack.Presentation.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: flaypack
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
